version: 0.2
phases:
  install:  
    commands: 
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands: 
      - echo "Initializing Terraform"
      - terraform init
  build:
    commands: 
      - echo "Destroying Terraform resources"
      - terraform destroy -auto-approve